site_name: Programming Notes
site_url: https://example.com/

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: default
      primary: blue
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    # - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking





extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ankits-dot/system-commands-notes
      name: Contribute on Github

plugins:
  - blog:
        post_date_format: full
        blog_dir: blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


#Information on How to navigate from the home page all parts of the website
nav:
  - Home: index.md
  - System Commands:
      - Home: system-commands/notes/index.md
      - Notes: system-commands/notes/index.md
      - Readings: system-commands/readings/index.md
      - Videos: system-commands/videos/index.md
      - Free MOOCs: system-commands/MOOCs/index.md
      - Problems: system-commands/problems/index.md
      - About the Course: system-commands/about/index.md
      - Credits: system-commands/credits/index.md
  # - PDSA: PDSA/index.md
  # - DBMS: DBMS/index.md
  # - MAD 1: mad-1/index.md
  # - MAD 2: mad-2/index.md
  # - Java: Java/index.md
  - How to Contribute: contribute/index.md



#using the below settings from mkdocs default theme   