site_name: Programming Notes
site_description: Readable material for Programming topics
site_url: https://ankits.live/programming-notes

# Repository
repo_name: ankits-dot/programming-notes
repo_url: https://github.com/ankits-dot/programming-notes
edit_uri: edit/unstable/docs/

# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - def_list


theme:
  name: material
  custom_dir: overrides
  favicon: assets/logo/logo.svg
  logo: assets/logo/logo.svg

  #shortcuts
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  highlightjs: true

  #when editing a page
  theme:
  icon:
    edit: material/pencil 
    view: material/eye

  palette:
    #light mode
    - scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    #dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - toc.integrate 






extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ankits-dot/system-commands-notes
      name: Contribute on Github

markdown_extensions:
  - toc:
      title: In this Week
      toc_depth: 2



plugins:
  - blog:
      post_date_format: full
      blog_dir: blog
      # post_dir: "{blog}/articles"
      archive_date_format: MMMM yyyy
      post_readtime: true
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: G-Y3M9M779JV

#Information on How to navigate from the home page all parts of the website
nav:
  - Home: index.md
  - System Commands:
      - About the Course: system-commands/about/index.md
      - Notes:
          - Week 1: system-commands/notes/Week-1/content.md
          - Week 2: system-commands/notes/Week-2/content.md
          - Week 3: system-commands/notes/Week-3/content.md
          - Week 4: system-commands/notes/Week-4/content.md
          - Week 5: system-commands/notes/Week-5/content.md
          - Week 6: system-commands/notes/Week-6/content.md
          - Week 7: system-commands/notes/Week-7/content.md
          - Week 8: system-commands/notes/Week-8/content.md


      - Readings: system-commands/readings/index.md
      - Videos: system-commands/videos/index.md
      - Free MOOCs: system-commands/MOOCs/index.md
      - Problems: system-commands/problems/index.md
      - Credits: system-commands/credits/index.md
  # - PDSA: PDSA/index.md
  # - DBMS: DBMS/index.md
  # - MAD 1: mad-1/index.md
  # - MAD 2: mad-2/index.md
  # - Java: Java/index.md
  - How to Contribute: contribute/index.md
  - Blog:
      - blog/index.md



#using the below settings from mkdocs default theme   